name: Build

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir -p build
      - uses: docker://pandoc/latex:2.12
        with:
          args: >-
            --resource-path=src
            --citeproc
            --csl=assets/citation-style.csl
            --from=markdown+tex_math_single_backslash+tex_math_dollars+raw_tex
            --to=latex
            --output=build/output_print.pdf
            --pdf-engine=xelatex
            --include-in-header="layout/print.tex"
            src/index.md
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/
