name: Esegui script build2 (non funziona)

on:
  push:
    #paths:
    #- 'content/**'
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Utilizza l'action github checkout@v2, per automatizzare il check-out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: installa pacchetti necessari
      run: |-
        sudo apt-get install -y pandoc
        #wget https://hackage.haskell.org/package/pandoc-1.17.0.3/pandoc-1.17.0.3.tar.gz
        #tar xvzf pandoc-1.17.0.3.tar.gz
        #cd pandoc-1.17.0.3
        sudo apt-get install -y pandoc-citeproc
        sudo apt-get install -y texlive-xetex
        sudo apt-get install -y texlive-luatex
        sudo apt-get install -y texlive-latex-extra
        sudo apt-get install -y texlive-latex-recommended
    - name: converti in pdf
      run: |-
        #cd ./script/provinciaCaltanissetta
        chmod +x ./build2.sh
        ./build2.sh
    - name: Committa e pusha
      run: |-
        git config user.name "automatico"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date --iso-8601=seconds)
        git commit -m "conversione: ${timestamp}" || exit 0
        git push
