name: aggiorna dati comuni provincia di Caltanissetta

on:
  push:
    paths:
    - 'content/**'
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Utilizza l'action github checkout@v2, per automatizzare il check-out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: installa pacchetti necessari
      run: |-
        sudo apt-get install -y pandoc
        sudo apt-get install texlive-xetex
    - name: converti in pdf
      run: |-
        #cd ./script/provinciaCaltanissetta
        chmod +x ./build2.sh
        ./build2.sh
    - name: Committa e pusha
      run: |-
        git config user.name "automatico"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date --iso-8601=seconds)
        git commit -m "conversione: ${timestamp}" || exit 0
        git push
