name: Build test commit

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Print output
        uses: docker://pandoc/latex:2.12
        with:
          args: >-
            content/index.md
            --resource-path=content
            --citeproc
            --csl=assets/citation-style.csl
            --from=markdown+tex_math_single_backslash+tex_math_dollars+raw_tex
            --to=latex
            --output=build/output_print.pdf
            --pdf-engine=xelatex
            --include-in-header=layouts/print.tex
      - name: Ereader output
        uses: docker://pandoc/latex:2.12
        with:
          args: >-
            content/index.md
            --resource-path=content
            --citeproc
            --csl=assets/citation-style.csl
            --from=markdown+tex_math_single_backslash+tex_math_dollars+raw_tex
            --to=latex
            --output=build/output_ereader.pdf
            --pdf-engine=xelatex
            --include-in-header=layouts/ereader.tex
      - uses: actions/checkout@v2
      - name: Committa e pusha
        run: |-
        git config user.name "automatico"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date --iso-8601=seconds)
        git commit -m "conversione: ${timestamp}" || exit 0
        git push

          
